### ISSUE TITLE
Switch from 'endroid/qr-code' to 'bacon/bacon-qr-code'

### ISSUE THREAD

**Issue by runelaenen** [runelaenen/shopware6-two-factor-auth#1]
The android package is a heavy-weight coming in at more than 16 megabytes. We'll switch to 'bacon/bacon-qr-code' which weighs under a megabyte.

To do
- [ ] Replace with bacon/bacon-qr-code

**Comment by BrentRobert** [comment]
I'll do this one (can't self assign)

**Comment by runelaenen** [comment]
Thank you for the help! 💙

**Comment by BrentRobert** [comment]
Which backend should be used for the library? As it creates new dependencies:
ImagickImageBackEnd: renders raster images using the Imagick library
SvgImageBackEnd: renders SVG files using XMLWriter
EpsImageBackEnd: renders EPS files

**Comment by runelaenen** [comment]
@BrentRobert SVG should be the best I think? Introduces the least 'heavy' dependencies it seems, and is supported on all devices.

**Comment by BrentRobert** [comment]
@runelaenen you can close this now
