### ISSUE TITLE
compiled files missing in release

### ISSUE THREAD

**Issue by tinect** [runelaenen/shopware6-two-factor-auth#29]
Maybe you want use:
https://github.com/FriendsOfShopware/platform-plugin-dev-docker

Or commit compiled files :thinking:

**Comment by runelaenen** [comment]
Ah that's what I was looking for. I knew I had seen a docker image to build plugins in CI somewhere, but was unable to find it when I was setting up the Github Actions.
Thanks! I'll be looking into this!

**Comment by runelaenen** [comment]
It looks like my test release went through perfectly 🥳 
I'll be looking at the PR later and will then create a new release with the correct builds.

**Comment by runelaenen** [comment]
Woops, referenced the wrong issue in my commit. But the action is running, and this should be fixed now :D
