### ISSUE TITLE
why for the -1 on my comment?

### ISSUE THREAD

**Issue by copremesis** [runelaenen/shopware6-two-factor-auth#31]
https://github.com/isaacs/github/issues/66#issuecomment-734077419

no likey dark reader?

**Comment by runelaenen** [comment]
Please don't create spam issues like this. I downvoted your comment because you should not use issues like that to advertise a chrome plugin. And seeing the other downvotes, I am not the only one thinking this.

**Comment by copremesis** [comment]
The hate is strong with this one .... I have no stock in the plugin ...
just saying ... keeping hating

**Comment by copremesis** [comment]
All good brother.... happy holidays
