### ISSUE TITLE
Dependencies are not being installed

### ISSUE THREAD

**Issue by gcascio** [runelaenen/shopware6-two-factor-auth#32]
When I try to install this plugin, I get the following error message:

```
Plugin could not be installed due to error message "Could not install plugin, got 2 failure(s).
Required plugin/package "pragmarx/google2fa ^8.0" is missing or not installed and activated
Required plugin/package "endroid/qr-code ^3.9" is missing or not installed and activated"
```

Maybe it is simply something I am missing out in the installation process? If so, I would be happy to contribute and update the README for future users.

EDIT: I am installing it locally using the repo

**Comment by runelaenen** [comment]
Either run composer install in the plugin directory, or use a packages release from the releases (and not the 'download zip' feature of GitHub)

Releases: https://github.com/runelaenen/shopware6-two-factor-auth/releases

**Comment by gcascio** [comment]
Thank you for the answer! I was unaware that the vendor folder has to be distributed with the plugin to make it work out of the box.
