### ISSUE TITLE
administration.js 404 not found

### ISSUE THREAD

**Issue by lavkshatriya** [runelaenen/shopware6-two-factor-auth#33]
If I activate this plugin it gives me a 404 error.
not created plugin folder in a public/bundle folder

**Comment by runelaenen** [comment]
How did you install the plugin? Did you use the release, or the 'Download zip' feature from Github?
You should use either composer (after which you will have to run your build script), or use the release zips. These release zips already contain the compiled javascripts.

The latest release zip can be found here: https://github.com/runelaenen/shopware6-two-factor-auth/releases/tag/v1.1.2
