### ISSUE TITLE
API route versions are no longer needed!

### ISSUE THREAD

**Issue by michnhokn** [runelaenen/shopware6-two-factor-auth#41]
https://github.com/runelaenen/shopware6-two-factor-auth/blob/126f16342b4a8e59c61af8f7f14dd49ca1d1c51b/src/Controller/TwoFactorAuthenticationApiController.php#L50

**Comment by michnhokn** [comment]
FYI: https://github.com/shopware/platform/blob/trunk/adr/2020-12-02-removing-api-version.md

**Comment by runelaenen** [comment]
This has been fixed in the latest release.
