### ISSUE TITLE
Nothing really works

### ISSUE THREAD

**Issue by wwwDESIGN-basti** [runelaenen/shopware6-two-factor-auth#43]
Hey,
i dont know but ive installed the plugin but nothing shows up in the backend.
In the Storefont, the 2FA shows up but nothing happend if i paste the single time password.

Is this plugin ready for SW 6.4.15.1?

**Comment by amenk** [comment]
I was told there is a fork which works with 6.4.16 :-) https://github.com/tinect/shopware6-two-factor-auth

**Comment by runelaenen** [comment]
Hi @wwwDESIGN-basti 

A new version has just been released with support for the latest versions.
