### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by runelaenen** [runelaenen/shopware6-two-factor-auth#5]
I'm only fluent in English and Dutch and thus can not provide a French translation.

**To do**
 - [ ] French translation for Administration snippets
 - [ ] French translation for Storefront snippets

**How to**
There are snippet files on 2 locations: `/src/Resources/app/administration/snippet` and `/src/Resources/snippet`
Both folders will have a Dutch and English version at the moment. You can copy the English file, rename it to reflect the correct language (`fr-FR`) and start translating.

**Comment by jessyprovencher** [comment]
Hi!

As a native French speaker, I would to contribute by translating both sections 🎉

**Comment by runelaenen** [comment]
Hi @jessyprovencher 

Thank you! That would be great!

In the German issue, you can find a quick 'how to get started' in case you have not worked with Shopware translations before.
https://github.com/runelaenen/shopware6-two-factor-auth/issues/2#issuecomment-678627617

Let me know if you need any help.

Of course, I do understand if you would like to wait until next week for Hacktoberfest ;) https://hacktoberfest.digitalocean.com/

**Comment by jessyprovencher** [comment]
Sure, thanks!

I'll wait until next week but it won't take long 👍

**Comment by tinect** [comment]
Isn't it ready to be integrated? :-)
