### ISSUE TITLE
! Password Change broken in 6.6.7.1

### ISSUE THREAD

**Issue by janobi** [runelaenen/shopware6-two-factor-auth#59]
We have a 6.6.7.1 shop with the plugin activated and observe that when administration users head to "Your profile" > "Password" and enter a new password, the field input is cleared immediately via the blur() event - on both the "new password" and "confirm password" fields. When they then click "Save", Shopware doesn't see any changes so nothing happens, other than an endless progress indicator on the "Save" button. This occurs regardless of whether or not this specific user has 2FA enabled, the plugin just has to be active in the shop.
Without the plugin activated, in the background, Shopware first sends a POST requests to retrieve a Bearer token, then a GET request to "/api/_info/config-me", then a PATCH to "/api/user/<user ID>" with the newly set password. With the plugin activated, that PATCH request does not occur since Shopware doesn't see any changes made.

We also observe that with the plugin active, non-administration users can get an error message saying that the "user:update" permission is missing (even with all "user" permissions granted to their role) when they try to change their password. This may be connected or a separate issue.

The unability to change one's administration password is a crititcal bug that should be addressed ASAP.

**Comment by tinect** [comment]
While this is an open-source project, you are welcome to contribute by a PR.

**Comment by runelaenen** [comment]
Hi, 6.0.1 was just released which should fix this issue.
