### ISSUE TITLE
Run administration without hot reload mode ends in a JavaScript error

### ISSUE THREAD

**Issue by mathiassname** [runelaenen/shopware6-two-factor-auth#9]
I download the latest tag and install / activate the plugin. After that, I access http://localhost:8000/admin and went in the following error:

<img width="773" alt="Bildschirmfoto 2020-08-24 um 14 06 11" src="https://user-images.githubusercontent.com/33735314/91043396-cc9f9900-e613-11ea-89e8-6b2216002484.png">

If I run the hot reload mode all is fine. Some idea or do you know the issue?

**Comment by runelaenen** [comment]
Have you ran the build for the administration javascript? `bin/build.sh`?
The committed files are not always in the git. If you want a 'upload and run' situation, you should download the zip release.

**Comment by mathiassname** [comment]
Yes, I tried to rebuild administration. In my case I take the files from GitHub, unzip them, copy them to the plugin folder. Add the required Composer packages and install the plugin on command line. After that I executed the build script of the  administration assets.

Now I tried to figure out the bug. After I commented out the line:

`// import './override/sw-settings-user/page/sw-settings-user-detail';`

the login works.

**Comment by scottie-33** [comment]
I had the same error.
After commented out the line there is no error at the login page, but also no settting-fields in the backend to enable 2FA.
Shopware Version: 6.3.0.2

**Comment by runelaenen** [comment]
I've been looking into this tonight, but I can't seem to reproduce this. I'm getting the same (good) result for the latest tagged version, as well as for the master, both in HRM as with a normal build.

**Comment by scottie-33** [comment]
I get this error with the download the zip release.
